### ISSUE TITLE
QC and ACE not respecting url exclusion pattern

### ISSUE THREAD

**Issue by ronnieg303** [websharks/comet-cache#356] opened 2014-10-16 05:11 UTC
My url exclusion pattern: /single-family-homes/*, meaning I do not want anything under that folder level to be cached. ACE is still pre-caching sub-pages under that folder level. But if I remove the \* at the end, then it seems to work as intended. It seems like both variations should work the same way. Just a minor issue, since it works one way but not the other.

**Comment by renzms** [comment] 2016-12-29 14:41
@raamdev 

### Unable to reproduce issue

WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentysixteen/
Active Plugins: Comet Cache Pro Version 161227 + Google XML Sitemaps Version 4.0.8
PHP Version: 7.0.10-2+deb.sury.org~xenial+1


**URL Exclusion Pattern**
>![screen shot 2016-12-29 at 10 37 37 pm](https://cloud.githubusercontent.com/assets/13220018/21546095/7ba763a6-ce17-11e6-9014-f8b9287b5343.png)

**Auto Cache Engine enabled**
>![screen shot 2016-12-29 at 10 37 24 pm](https://cloud.githubusercontent.com/assets/13220018/21546096/7ba9fc74-ce17-11e6-933f-e66f59fe7d93.png)


**`/single-family-homes/*` is not Cached**

>![screen shot 2016-12-29 at 10 36 50 pm](https://cloud.githubusercontent.com/assets/13220018/21546097/7bafdc02-ce17-11e6-935a-cb65ca122d9d.png)

**Also not found in Cache Category Directory**
>![screen shot 2016-12-29 at 10 32 47 pm](https://cloud.githubusercontent.com/assets/13220018/21546098/7bb232cc-ce17-11e6-8ddd-9884ee8611a0.png)

**Comment by raamdev** [comment] 2016-12-29 19:27
@renzms You did verify that _other_ pages _were_ cached by the Auto-Cache Engine, correct? I just want to make sure that you confirmed the Auto-Cache Engine actually ran and _then_ checked to make sure that it didn't cache the excluded pages.

**Comment by renzms** [comment] 2016-12-30 05:06
@raamdev 

Yes, the Auto-Cache Engine ran and cached all the other pages from the Sitemap including the other categories. The screenshot I provided above shows the other category called `1` and the `Uncategorized` category to show that it did in fact skip caching category: `single-family-homes/*`

**Comment by raamdev** [comment] 2016-12-30 17:37
@renzms Thank you! :-) I'll close this as `cannot reproduce`.

**Closed by raamdev** 2016-12-30 17:37 UTC
Labels: auto-cache engine, bug, needs testing, pro
